spring:
  base-url: "https://www.zlearn.io.vn"
  admin-pass: "nhom2vippro"
  application:
    name: ptit-checkin
  datasource:
    url: jdbc:mysql://localhost:3306/db_v1
    username: root
    password: Hcn14022004.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration

server:
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    session:
      timeout: 120m
      cookie:
        max-age: 86400
        http-only: true
        secure: true