
spring:
  application:
    name: ptit-checkin
  datasource:
    url: jdbc:mysql://localhost:3306/db_v1
    username: root
    password: Hcn14022004.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration