
spring:
  application:
    name: ptit-checkin
  datasource:
    url: jdbc:mysql://localhost:3306/db_v1
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration

server:
  error:
    whitelabel:
      enabled: false
    path: /error
  servlet:
    session:
      timeout: 60m        # Thời gian timeout của session
      cookie:
        max-age: 86400    # Thời gian sống của cookie (86400 giây = 1 ngày)
        http-only: true   # Kích hoạt HttpOnly
        secure: true      # (Tùy chọn) Bảo mật cookie qua HTTPS